using System.Collections.Generic;

namespace ScriptCompiler.NetFramework
{
    internal static class RuntimeProvidedAssemblies
    {
        /// <summary>
        /// Checks whether the set of known runtime assemblies contains the given assembly name.
        /// </summary>
        /// <param name="assembly">The assembly name.</param>
        /// <returns>True if the assembly is provided by the framework, otherwise false.</returns>
        public static bool IsAssemblyProvidedByRuntime(string assembly)
        {
            return ProvidedAssemblies.Contains(assembly);
        }
        /*<# foreach (var filename in System.IO.Directory.GetFiles(@"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8", "*.dll"))
           { #>
        "<#= filename.Split('\\').Last() #>",
        <# } #>*/
        /// <summary>
        /// This list comes from C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8
        /// If the executing binaries ever change to a newer version, this project must update as well, and refresh this list.
        /// </summary>
        private static readonly ISet<string> ProvidedAssemblies = new HashSet<string>
        {
            "Accessibility.dll",
            "CustomMarshalers.dll",
            "ISymWrapper.dll",
            "Microsoft.Activities.Build.dll",
            "Microsoft.Build.Conversion.v4.0.dll",
            "Microsoft.Build.dll",
            "Microsoft.Build.Engine.dll",
            "Microsoft.Build.Framework.dll",
            "Microsoft.Build.Tasks.v4.0.dll",
            "Microsoft.Build.Utilities.v4.0.dll",
            "Microsoft.CSharp.dll",
            "Microsoft.JScript.dll",
            "Microsoft.VisualBasic.Compatibility.Data.dll",
            "Microsoft.VisualBasic.Compatibility.dll",
            "Microsoft.VisualBasic.dll",
            "Microsoft.VisualC.dll",
            "Microsoft.VisualC.STLCLR.dll",
            "mscorlib.dll",
            "PresentationBuildTasks.dll",
            "PresentationCore.dll",
            "PresentationFramework.Aero.dll",
            "PresentationFramework.Aero2.dll",
            "PresentationFramework.AeroLite.dll",
            "PresentationFramework.Classic.dll",
            "PresentationFramework.dll",
            "PresentationFramework.Luna.dll",
            "PresentationFramework.Royale.dll",
            "ReachFramework.dll",
            "sysglobl.dll",
            "System.Activities.Core.Presentation.dll",
            "System.Activities.dll",
            "System.Activities.DurableInstancing.dll",
            "System.Activities.Presentation.dll",
            "System.AddIn.Contract.dll",
            "System.AddIn.dll",
            "System.ComponentModel.Composition.dll",
            "System.ComponentModel.Composition.Registration.dll",
            "System.ComponentModel.DataAnnotations.dll",
            "System.Configuration.dll",
            "System.Configuration.Install.dll",
            "System.Core.dll",
            "System.Data.DataSetExtensions.dll",
            "System.Data.dll",
            "System.Data.Entity.Design.dll",
            "System.Data.Entity.dll",
            "System.Data.Linq.dll",
            "System.Data.OracleClient.dll",
            "System.Data.Services.Client.dll",
            "System.Data.Services.Design.dll",
            "System.Data.Services.dll",
            "System.Data.SqlXml.dll",
            "System.Deployment.dll",
            "System.Design.dll",
            "System.Device.dll",
            "System.Diagnostics.Tracing.dll",
            "System.DirectoryServices.AccountManagement.dll",
            "System.DirectoryServices.dll",
            "System.DirectoryServices.Protocols.dll",
            "System.dll",
            "System.Drawing.Design.dll",
            "System.Drawing.dll",
            "System.Dynamic.dll",
            "System.EnterpriseServices.dll",
            "System.EnterpriseServices.Thunk.dll",
            "System.EnterpriseServices.Wrapper.dll",
            "System.IdentityModel.dll",
            "System.IdentityModel.Selectors.dll",
            "System.IdentityModel.Services.dll",
            "System.IO.Compression.dll",
            "System.IO.Compression.FileSystem.dll",
            "System.IO.Log.dll",
            "System.Management.dll",
            "System.Management.Instrumentation.dll",
            "System.Messaging.dll",
            "System.Net.dll",
            "System.Net.Http.dll",
            "System.Net.Http.WebRequest.dll",
            "System.Numerics.dll",
            "System.Printing.dll",
            "System.Reflection.Context.dll",
            "System.Runtime.Caching.dll",
            "System.Runtime.DurableInstancing.dll",
            "System.Runtime.Remoting.dll",
            "System.Runtime.Serialization.dll",
            "System.Runtime.Serialization.Formatters.Soap.dll",
            "System.Security.dll",
            "System.ServiceModel.Activation.dll",
            "System.ServiceModel.Activities.dll",
            "System.ServiceModel.Channels.dll",
            "System.ServiceModel.Discovery.dll",
            "System.ServiceModel.dll",
            "System.ServiceModel.Routing.dll",
            "System.ServiceModel.Web.dll",
            "System.ServiceProcess.dll",
            "System.Speech.dll",
            "System.Transactions.dll",
            "System.Web.Abstractions.dll",
            "System.Web.ApplicationServices.dll",
            "System.Web.DataVisualization.Design.dll",
            "System.Web.DataVisualization.dll",
            "System.Web.dll",
            "System.Web.DynamicData.Design.dll",
            "System.Web.DynamicData.dll",
            "System.Web.Entity.Design.dll",
            "System.Web.Entity.dll",
            "System.Web.Extensions.Design.dll",
            "System.Web.Extensions.dll",
            "System.Web.Mobile.dll",
            "System.Web.RegularExpressions.dll",
            "System.Web.Routing.dll",
            "System.Web.Services.dll",
            "System.Windows.Controls.Ribbon.dll",
            "System.Windows.dll",
            "System.Windows.Forms.DataVisualization.Design.dll",
            "System.Windows.Forms.DataVisualization.dll",
            "System.Windows.Forms.dll",
            "System.Windows.Input.Manipulations.dll",
            "System.Windows.Presentation.dll",
            "System.Workflow.Activities.dll",
            "System.Workflow.ComponentModel.dll",
            "System.Workflow.Runtime.dll",
            "System.WorkflowServices.dll",
            "System.Xaml.dll",
            "System.Xml.dll",
            "System.Xml.Linq.dll",
            "System.Xml.Serialization.dll",
            "UIAutomationClient.dll",
            "UIAutomationClientsideProviders.dll",
            "UIAutomationProvider.dll",
            "UIAutomationTypes.dll",
            "WindowsBase.dll",
            "WindowsFormsIntegration.dll",
            "XamlBuildTask.dll",
        };
    }
}
